PREFIX dct: <http://purl.org/dc/terms/>
PREFIX evt: <http://eventour.unimib.it/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>


# CQ1. How many Wikidata-derived semantic places are available for each
# Eventour role?
################################################################################

SELECT ?role ?roleLabel (COUNT(DISTINCT ?place) AS ?places)
WHERE {
  ?place a evt:Place ;
         evt:hasEventourRole ?role .
  OPTIONAL { ?role skos:prefLabel ?roleLabel . }
}
GROUP BY ?role ?roleLabel
ORDER BY DESC(?places)

################################################################################
