PREFIX dct: <http://purl.org/dc/terms/>
PREFIX evt: <http://eventour.unimib.it/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>


# CQ2. Which Eventour entities are located in a given NIL area, including
# official city entities and Wikidata semantic places?
################################################################################

SELECT ?entity ?label ?class ?role ?roleLabel ?wkt
WHERE {
  VALUES ?nil {
    <http://eventour.unimib.it/milan/nil/1>
  }

  ?entity evt:inNIL ?nil ;
          a ?class ;
          geo:hasDefaultGeometry/geo:asWKT ?wkt .
  OPTIONAL { ?entity rdfs:label ?label . }
  OPTIONAL {
    ?entity evt:hasEventourRole ?role .
    OPTIONAL { ?role skos:prefLabel ?roleLabel . }
  }
}
ORDER BY ?class LCASE(STR(?label))
LIMIT 500

################################################################################
