PREFIX dct: <http://purl.org/dc/terms/>
PREFIX evt: <http://eventour.unimib.it/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>


# CQ4. For each primary POI, which public toilets and drinking fountains are
# available within 250 metres?
# Requires GeoSPARQL distance support.
################################################################################

SELECT ?poi ?poiLabel ?service ?serviceLabel ?serviceType ?distanceM
WHERE {
  ?poi a evt:Place ;
       evt:hasEventourRole <http://eventour.unimib.it/role/primary-poi> ;
       rdfs:label ?poiLabel ;
       geo:hasDefaultGeometry/geo:asWKT ?poiWKT .

  VALUES (?serviceType ?serviceClass) {
    ("public toilet" evt:PublicToilet)
    ("drinking fountain" evt:DrinkingFountain)
  }

  ?service a ?serviceClass ;
           rdfs:label ?serviceLabel ;
           geo:hasDefaultGeometry/geo:asWKT ?serviceWKT .

  BIND(geof:distance(?poiWKT, ?serviceWKT, uom:metre) AS ?distanceM)
  FILTER(?distanceM <= 250)
}
ORDER BY ?poiLabel ?serviceType ?distanceM
LIMIT 300

################################################################################
