PREFIX dct: <http://purl.org/dc/terms/>
PREFIX evt: <http://eventour.unimib.it/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>


# CQ7. Which primary POIs are underserved, i.e., have no public toilet or
# drinking fountain within 300 metres?
# Requires GeoSPARQL distance support.
################################################################################

SELECT ?poi ?label ?categoryLabel
WHERE {
  ?poi a evt:Place ;
       evt:hasEventourRole <http://eventour.unimib.it/role/primary-poi> ;
       rdfs:label ?label ;
       geo:hasDefaultGeometry/geo:asWKT ?poiWKT .
  OPTIONAL {
    ?poi evt:hasEventourCategory/skos:prefLabel ?categoryLabel .
  }

  FILTER NOT EXISTS {
    VALUES ?serviceClass { evt:PublicToilet evt:DrinkingFountain }
    ?service a ?serviceClass ;
             geo:hasDefaultGeometry/geo:asWKT ?serviceWKT .
    BIND(geof:distance(?poiWKT, ?serviceWKT, uom:metre) AS ?distanceM)
    FILTER(?distanceM <= 300)
  }
}
ORDER BY LCASE(STR(?label))
LIMIT 100

################################################################################
