PREFIX dct: <http://purl.org/dc/terms/>
PREFIX evt: <http://eventour.unimib.it/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>


# CQ9. Provenance audit: for a selected entity, retrieve source dataset,
# source record, generation activity, and external Wikidata link if present.
################################################################################

SELECT ?entity ?label ?source ?sourceRecord ?activity ?wikidata
WHERE {
  VALUES ?entity {
    <http://eventour.unimib.it/milan/entity/wikidata/Q10986>
  }
  OPTIONAL { ?entity rdfs:label ?label . }
  OPTIONAL { ?entity dct:source ?source . }
  OPTIONAL { ?entity prov:wasDerivedFrom ?sourceRecord . }
  OPTIONAL { ?entity prov:wasGeneratedBy ?activity . }
  OPTIONAL { ?entity owl:sameAs ?wikidata . }
}

################################################################################
