from types import MappingProxyType


CANONICAL_COLUMNS = (
    "source_dataset_name",
    "source_record_key",
    "stable_identifier",
    "secondary_identifier",
    "composite_identifier",
    "entity_family",
    "entity_subtype",
    "transport_mode",
    "label",
    "label_construction_rule",
    "street_code",
    "street_type",
    "street_name",
    "street_number",
    "full_address",
    "locality_text",
    "placement_context",
    "municipio",
    "nil_id",
    "nil_name",
    "sub_nil_id",
    "postal_code",
    "zone_or_ring",
    "city_name",
    "source_area_id",
    "area_code",
    "parking_ambit_id",
    "parking_ambit_name",
    "geometry_type",
    "longitude",
    "latitude",
    "wkt_geometry",
    "source_coordinate_text",
    "status",
    "availability_window",
    "valid_from",
    "valid_to",
    "year_or_installation_date",
    "source_reference",
    "notes",
    "operator",
    "allowed_vehicle_category",
    "installation_or_infrastructure_type",
    "category_text",
    "capacity_total",
    "capacity_per_unit",
    "num_structures",
    "raw_capacity_text",
    "project_name",
    "ordinance",
    "botanical_genus",
    "botanical_species",
    "botanical_variety",
    "trunk_diameter",
    "crown_diameter",
    "height_m",
    "geometry_length_source",
    "geometry_area_source",
    "line_code",
    "route_code",
    "route_name",
    "direction_code",
    "route_type",
    "route_length_km",
    "stop_count",
    "stop_id_reference",
    "sequence_number",
    "interchange_info",
    "day_type",
    "timetable_period",
    "service_start_time",
    "service_end_time",
    "trip_count_total",
    "trip_count_peak",
    "trip_count_offpeak",
    "trip_count_evening",
)

_COLUMN_GROUPS = {
    "identity": (
        "source_dataset_name",
        "source_record_key",
        "stable_identifier",
        "secondary_identifier",
        "composite_identifier",
    ),
    "typing": (
        "entity_family",
        "entity_subtype",
        "transport_mode",
    ),
    "labeling": (
        "label",
        "label_construction_rule",
    ),
    "addressing": (
        "street_code",
        "street_type",
        "street_name",
        "street_number",
        "full_address",
        "locality_text",
        "placement_context",
    ),
    "administrative": (
        "municipio",
        "nil_id",
        "nil_name",
        "sub_nil_id",
        "postal_code",
        "zone_or_ring",
        "city_name",
        "source_area_id",
        "area_code",
        "parking_ambit_id",
        "parking_ambit_name",
    ),
    "geometry": (
        "geometry_type",
        "longitude",
        "latitude",
        "wkt_geometry",
        "source_coordinate_text",
        "geometry_length_source",
        "geometry_area_source",
    ),
    "operational": (
        "status",
        "availability_window",
        "valid_from",
        "valid_to",
        "year_or_installation_date",
        "source_reference",
        "notes",
        "operator",
        "allowed_vehicle_category",
        "installation_or_infrastructure_type",
        "category_text",
    ),
    "capacity": (
        "capacity_total",
        "capacity_per_unit",
        "num_structures",
        "raw_capacity_text",
        "project_name",
        "ordinance",
    ),
    "botanical": (
        "botanical_genus",
        "botanical_species",
        "botanical_variety",
        "trunk_diameter",
        "crown_diameter",
        "height_m",
    ),
    "transport": (
        "line_code",
        "route_code",
        "route_name",
        "direction_code",
        "route_type",
        "route_length_km",
        "stop_count",
        "stop_id_reference",
        "sequence_number",
        "interchange_info",
    ),
    "timetable": (
        "day_type",
        "timetable_period",
        "service_start_time",
        "service_end_time",
        "trip_count_total",
        "trip_count_peak",
        "trip_count_offpeak",
        "trip_count_evening",
    ),
}

COLUMN_GROUPS = MappingProxyType(_COLUMN_GROUPS)
EMPTY_ROW_TEMPLATE = MappingProxyType({column: None for column in CANONICAL_COLUMNS})
