PREFIX evt: <http://eventour.unimib.it/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?nil ?nilLabel
       (COUNT(DISTINCT ?fountain) AS ?fountains)
       (COUNT(DISTINCT ?bench) AS ?benches)
       (COUNT(DISTINCT ?picnicTable) AS ?picnicTables)
WHERE {
  ?nil a evt:NILArea .
  OPTIONAL { ?nil rdfs:label ?nilLabel . }
  OPTIONAL { ?fountain a evt:DrinkingFountain ; evt:inNIL ?nil . }
  OPTIONAL { ?bench a evt:Bench ; evt:inNIL ?nil . }
  OPTIONAL { ?picnicTable a evt:PicnicTable ; evt:inNIL ?nil . }
}
GROUP BY ?nil ?nilLabel
ORDER BY DESC(?fountains + ?benches + ?picnicTables)
LIMIT 50

