PREFIX evt: <http://eventour.unimib.it/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>

SELECT ?candidate ?label ?distanceM
WHERE {
  VALUES ?eventWKT { "POINT (9.1919 45.4642)"^^geo:wktLiteral }
  ?candidate a evt:Place ;
      evt:hasEventourRole <http://eventour.unimib.it/role/secondary-poi> ;
      rdfs:label ?label ;
      geo:hasDefaultGeometry/geo:asWKT ?wkt .
  BIND(geof:distance(?eventWKT, ?wkt, uom:metre) AS ?distanceM)
  FILTER(?distanceM <= 1000)
}
ORDER BY ?distanceM
LIMIT 100

